OpenClassrooms-Student-Center/alumnis

content/students/guillaume.md
Modification du lien du projet 2 !
=> Changement du link

content/students/yann.md
je pense avoir trouvé mon erreur et je l'ai modifié, mon erreur était dans le lien j'avais laissé ratus au lieu de mettre mon prénom
merci d'avance
=> modification fichier yann.md

content/students/yann.md
Bonjour,
vu que je ne trouvais pas mon erreur, j'ai tout refait, en espérant que cela a rectifié ma faute. maintenant que je vois mon pull request je pense avoir trouvé mon erreur.
Cela doit être à cause de templates qui n'etais pas situé au bon endroit
merci d'avance
=> J'ai refait mon dossier car une erreur

content/students/yann.md
J'ai rectifié l'accent sur le e et ratus pour le projet 3
=> rectification accent sur un e

content/students/yann.md
Je pense avoir trouvé mon erreur.
Désolé pour le dérangement
=> j'ai rectifié mon lien

content/students/yann.md
j'ai fait comme vous m'avez dit et mis mon lien profile github
=> mis en ligne lien profil github

content/students/matthieu44.md
=> Ajout de la majuscule au mot True

content/students/spencer.md
Student in the "DA iOS" path.
Updating spencer.md
=> Updated URL for my OC student profile

content/students/mylene.md
=> Mylene - Suppression lignes inutiles

content/students/mylene.md
Bonjour, 
J'ai rectifié le fichier .md (je suis partie d'un nouveau document et j'ai pris le template comme demandé !)
Je croise les doigts !
=> rectification du fichier mylene.md à neuf

content/students/mylene.md
Bonjour, 
Voici les dernières modifications
=> dernieres modifications sur md

content/students/florian31.md
Remplacement de "j'ai" par "je"
=> Dans le fichier florian31 correction ligne 21

content/students/ludovicgros1.md
Modification du ludovicgros1.jpg en .png
=> Rectification image sur ludovicgros1.md

content/students/ludovicgros1.md
Description lorem retiré pour ajout description perso et modification du lien projet intégrer la communauté pour rediriger vers github perso
=> Modification description et changement du lien 

content/students/Radohery.md
Modifier un projet open source
=> Radohery.md

content/students/mathieu9.md
Correction de la date de mon fichier .md.
=> Mise à jour de la date dans mon fichier .md

content/students/antony.md
Soutenance du projet 3 validée.
Modification content/students/antony.md pour actualiser statut.
=> validation du projet 3

content/students/daniel.md
=> Correction extension image portrait

content/students/Martin.md
=> Modifier destination image

matthieuC.md
Bonjour,
Merci d'ajouter mon fichier matthieuC.md
Cordialement
Matthieu C
=> Ajout de mon fichier matthieuC

content/students/etienne86.md
Bonjour,
J'ai modifié mon fichier etienne86.md.
Je vous remercie d'avance de bien vouloir vérifier si cette demande est conforme, afin de l'intégrer.
Bonne journée !
Etienne
=> Modification de etienne86.md

content/students/ottakar.md
ADD content/students/ottakar.md
repo freezed/alumnis
=> Ajout de l'eleve ottakar

content/students/mohammedmorchikh.md
Bonjour, 
Le fichier est corrigé, merci de le merger.
A bientôt
=> Fichier corrigé

gilles.md
Salut les gars, 
faîtes moi un super retour démolition
tout ce qui ne va pas "bazookez-le" (mot d'origine greco-je sais pas)
Thanks
=>  gilles.md

content/students/mohammedmorchikh.md
=> modification du fichier .md

openclassrooms/static/js/scripts.js, openclassrooms/templates/index.html, openclassrooms/templates/students.html
Add JS function to replace non-existent images with generic image
=> Add JS function to replace non-existent images with generic image

openclassrooms/static/js/scripts.js, openclassrooms/templates/index.html
Add JS to deal with pagination on index page.
I was inspired by the OC bootstrap course (pagination example).
=> Add JS to deal with pagination on index page

openclassrooms/static/js/scripts.js
Change default generic image src url with absolute one.
=> Change default generic image src url with absolute one.

content/students/maxime21.md
Bonjour,
Voici ma nouvelle version du livrable du projet 2  "Intégrez la communauté OpenClassrooms".
J'ai apporté plusieurs modifications au fichier maxime21.md: 
-corrections des chemins vers images pour les 2 premiers projets
-ajout d'une brève description
-ajout de liens vers linkedIn et Github
Maxime SORO
=> Livrable projet 2 java/java EE et corrections 

content/students/david9496.md
Ajout de l'étudiant David (david9496.md)
=> Ajout de david9496.md

content/students/hakan7A
Bonjour, j'ai rajouté ma présentation, merci de le prendre en compte
=> Ajout de mon projet

content/students/sophie.md
description et short description, lien vers la page alumni, suppression 3ème projet.
=> Quelques modifs dans le fichier MD :

content/students/davidchosrova.md
Added all projects, and link in projects.
@MrDiben
=> Updated description

content/students/alaindesombre.md
Le bot Travis n'est pas passé et l'erreur de formating m'a échappé.
=> Fix alaindesombre.md
